apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: convert
  template:
    metadata:
      labels:
        app: convert
    spec:
      containers:
      - name: conversao
        image: rangelcr/conversao-temperatura
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
--- 
apiVersion: v1
kind: Service
metadata:
  name: convert
spec:
  selector:
    app: convert
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer