apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: hml

resources:
  - ../../base

images:
  - name: rangelcr/conversao-temperatura
    newTag: "latest"

patches:
  - path: patch.yaml
